/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as AuthenticatedAppRouteImport } from './routes/_authenticated/app'
import { Route as AuthenticatedAppIndexRouteImport } from './routes/_authenticated/app.index'
import { Route as AuthenticatedAppActionPlanRouteImport } from './routes/_authenticated/app.action-plan'
import { Route as AuthenticatedAppAiUsageRouteImport } from './routes/_authenticated/app.ai-usage'
import { Route as AuthenticatedAppBlueprintRouteImport } from './routes/_authenticated/app.blueprint'
import { Route as AuthenticatedAppBrainRouteImport } from './routes/_authenticated/app.brain'
import { Route as AuthenticatedAppCustomersRouteImport } from './routes/_authenticated/app.customers'
import { Route as AuthenticatedAppDashboardRouteImport } from './routes/_authenticated/app.dashboard'
import { Route as AuthenticatedAppDiagnosisRouteImport } from './routes/_authenticated/app.diagnosis'
import { Route as AuthenticatedAppExperimentsRouteImport } from './routes/_authenticated/app.experiments'
import { Route as AuthenticatedAppHelpRouteImport } from './routes/_authenticated/app.help'
import { Route as AuthenticatedAppInterviewRouteImport } from './routes/_authenticated/app.interview'
import { Route as AuthenticatedAppLeadsRouteImport } from './routes/_authenticated/app.leads'
import { Route as AuthenticatedAppMetricsRouteImport } from './routes/_authenticated/app.metrics'
import { Route as AuthenticatedAppNotificationsRouteImport } from './routes/_authenticated/app.notifications'
import { Route as AuthenticatedAppOffersRouteImport } from './routes/_authenticated/app.offers'
import { Route as AuthenticatedAppSeoRouteImport } from './routes/_authenticated/app.seo'
import { Route as AuthenticatedAppServicesRouteImport } from './routes/_authenticated/app.services'
import { Route as AuthenticatedAppSettingsRouteImport } from './routes/_authenticated/app.settings'
import { Route as AuthenticatedBusinessNewRouteImport } from './routes/_authenticated/business.new'
import { Route as AuthenticatedBusinessSelectRouteImport } from './routes/_authenticated/business.select'
import { Route as ApiPublicAiJobsWorkerRouteImport } from './routes/api/public/ai-jobs-worker'
import { Route as AuthenticatedAppMetricsIndexRouteImport } from './routes/_authenticated/app.metrics.index'
import { Route as AuthenticatedAppMetricsMetricIdRouteImport } from './routes/_authenticated/app.metrics.$metricId'
import { Route as AuthenticatedAppOperationsIndexRouteImport } from './routes/_authenticated/app.operations.index'
import { Route as AuthenticatedAppOperationsProcessIdRouteImport } from './routes/_authenticated/app.operations.$processId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAppRoute = AuthenticatedAppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAppIndexRoute = AuthenticatedAppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAppActionPlanRoute =
  AuthenticatedAppActionPlanRouteImport.update({
    id: '/action-plan',
    path: '/action-plan',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppAiUsageRoute = AuthenticatedAppAiUsageRouteImport.update({
  id: '/ai-usage',
  path: '/ai-usage',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAppBlueprintRoute =
  AuthenticatedAppBlueprintRouteImport.update({
    id: '/blueprint',
    path: '/blueprint',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppBrainRoute = AuthenticatedAppBrainRouteImport.update({
  id: '/brain',
  path: '/brain',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAppCustomersRoute =
  AuthenticatedAppCustomersRouteImport.update({
    id: '/customers',
    path: '/customers',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppDashboardRoute =
  AuthenticatedAppDashboardRouteImport.update({
    id: '/dashboard',
    path: '/dashboard',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppDiagnosisRoute =
  AuthenticatedAppDiagnosisRouteImport.update({
    id: '/diagnosis',
    path: '/diagnosis',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppExperimentsRoute =
  AuthenticatedAppExperimentsRouteImport.update({
    id: '/experiments',
    path: '/experiments',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppHelpRoute = AuthenticatedAppHelpRouteImport.update({
  id: '/help',
  path: '/help',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAppInterviewRoute =
  AuthenticatedAppInterviewRouteImport.update({
    id: '/interview',
    path: '/interview',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppLeadsRoute = AuthenticatedAppLeadsRouteImport.update({
  id: '/leads',
  path: '/leads',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAppMetricsRoute = AuthenticatedAppMetricsRouteImport.update({
  id: '/metrics',
  path: '/metrics',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAppNotificationsRoute =
  AuthenticatedAppNotificationsRouteImport.update({
    id: '/notifications',
    path: '/notifications',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppOffersRoute = AuthenticatedAppOffersRouteImport.update({
  id: '/offers',
  path: '/offers',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAppSeoRoute = AuthenticatedAppSeoRouteImport.update({
  id: '/seo',
  path: '/seo',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAppServicesRoute =
  AuthenticatedAppServicesRouteImport.update({
    id: '/services',
    path: '/services',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppSettingsRoute =
  AuthenticatedAppSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedBusinessNewRoute =
  AuthenticatedBusinessNewRouteImport.update({
    id: '/business/new',
    path: '/business/new',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedBusinessSelectRoute =
  AuthenticatedBusinessSelectRouteImport.update({
    id: '/business/select',
    path: '/business/select',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const ApiPublicAiJobsWorkerRoute = ApiPublicAiJobsWorkerRouteImport.update({
  id: '/api/public/ai-jobs-worker',
  path: '/api/public/ai-jobs-worker',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAppMetricsIndexRoute =
  AuthenticatedAppMetricsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedAppMetricsRoute,
  } as any)
const AuthenticatedAppMetricsMetricIdRoute =
  AuthenticatedAppMetricsMetricIdRouteImport.update({
    id: '/$metricId',
    path: '/$metricId',
    getParentRoute: () => AuthenticatedAppMetricsRoute,
  } as any)
const AuthenticatedAppOperationsIndexRoute =
  AuthenticatedAppOperationsIndexRouteImport.update({
    id: '/operations/',
    path: '/operations/',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppOperationsProcessIdRoute =
  AuthenticatedAppOperationsProcessIdRouteImport.update({
    id: '/operations/$processId',
    path: '/operations/$processId',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/app': typeof AuthenticatedAppRouteWithChildren
  '/app/action-plan': typeof AuthenticatedAppActionPlanRoute
  '/app/ai-usage': typeof AuthenticatedAppAiUsageRoute
  '/app/blueprint': typeof AuthenticatedAppBlueprintRoute
  '/app/brain': typeof AuthenticatedAppBrainRoute
  '/app/customers': typeof AuthenticatedAppCustomersRoute
  '/app/dashboard': typeof AuthenticatedAppDashboardRoute
  '/app/diagnosis': typeof AuthenticatedAppDiagnosisRoute
  '/app/experiments': typeof AuthenticatedAppExperimentsRoute
  '/app/help': typeof AuthenticatedAppHelpRoute
  '/app/interview': typeof AuthenticatedAppInterviewRoute
  '/app/leads': typeof AuthenticatedAppLeadsRoute
  '/app/metrics': typeof AuthenticatedAppMetricsRouteWithChildren
  '/app/notifications': typeof AuthenticatedAppNotificationsRoute
  '/app/offers': typeof AuthenticatedAppOffersRoute
  '/app/seo': typeof AuthenticatedAppSeoRoute
  '/app/services': typeof AuthenticatedAppServicesRoute
  '/app/settings': typeof AuthenticatedAppSettingsRoute
  '/business/new': typeof AuthenticatedBusinessNewRoute
  '/business/select': typeof AuthenticatedBusinessSelectRoute
  '/api/public/ai-jobs-worker': typeof ApiPublicAiJobsWorkerRoute
  '/app/': typeof AuthenticatedAppIndexRoute
  '/app/metrics/$metricId': typeof AuthenticatedAppMetricsMetricIdRoute
  '/app/operations/$processId': typeof AuthenticatedAppOperationsProcessIdRoute
  '/app/metrics/': typeof AuthenticatedAppMetricsIndexRoute
  '/app/operations/': typeof AuthenticatedAppOperationsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/app/action-plan': typeof AuthenticatedAppActionPlanRoute
  '/app/ai-usage': typeof AuthenticatedAppAiUsageRoute
  '/app/blueprint': typeof AuthenticatedAppBlueprintRoute
  '/app/brain': typeof AuthenticatedAppBrainRoute
  '/app/customers': typeof AuthenticatedAppCustomersRoute
  '/app/dashboard': typeof AuthenticatedAppDashboardRoute
  '/app/diagnosis': typeof AuthenticatedAppDiagnosisRoute
  '/app/experiments': typeof AuthenticatedAppExperimentsRoute
  '/app/help': typeof AuthenticatedAppHelpRoute
  '/app/interview': typeof AuthenticatedAppInterviewRoute
  '/app/leads': typeof AuthenticatedAppLeadsRoute
  '/app/notifications': typeof AuthenticatedAppNotificationsRoute
  '/app/offers': typeof AuthenticatedAppOffersRoute
  '/app/seo': typeof AuthenticatedAppSeoRoute
  '/app/services': typeof AuthenticatedAppServicesRoute
  '/app/settings': typeof AuthenticatedAppSettingsRoute
  '/business/new': typeof AuthenticatedBusinessNewRoute
  '/business/select': typeof AuthenticatedBusinessSelectRoute
  '/api/public/ai-jobs-worker': typeof ApiPublicAiJobsWorkerRoute
  '/app': typeof AuthenticatedAppIndexRoute
  '/app/metrics/$metricId': typeof AuthenticatedAppMetricsMetricIdRoute
  '/app/operations/$processId': typeof AuthenticatedAppOperationsProcessIdRoute
  '/app/metrics': typeof AuthenticatedAppMetricsIndexRoute
  '/app/operations': typeof AuthenticatedAppOperationsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/_authenticated/app': typeof AuthenticatedAppRouteWithChildren
  '/_authenticated/app/action-plan': typeof AuthenticatedAppActionPlanRoute
  '/_authenticated/app/ai-usage': typeof AuthenticatedAppAiUsageRoute
  '/_authenticated/app/blueprint': typeof AuthenticatedAppBlueprintRoute
  '/_authenticated/app/brain': typeof AuthenticatedAppBrainRoute
  '/_authenticated/app/customers': typeof AuthenticatedAppCustomersRoute
  '/_authenticated/app/dashboard': typeof AuthenticatedAppDashboardRoute
  '/_authenticated/app/diagnosis': typeof AuthenticatedAppDiagnosisRoute
  '/_authenticated/app/experiments': typeof AuthenticatedAppExperimentsRoute
  '/_authenticated/app/help': typeof AuthenticatedAppHelpRoute
  '/_authenticated/app/interview': typeof AuthenticatedAppInterviewRoute
  '/_authenticated/app/leads': typeof AuthenticatedAppLeadsRoute
  '/_authenticated/app/metrics': typeof AuthenticatedAppMetricsRouteWithChildren
  '/_authenticated/app/notifications': typeof AuthenticatedAppNotificationsRoute
  '/_authenticated/app/offers': typeof AuthenticatedAppOffersRoute
  '/_authenticated/app/seo': typeof AuthenticatedAppSeoRoute
  '/_authenticated/app/services': typeof AuthenticatedAppServicesRoute
  '/_authenticated/app/settings': typeof AuthenticatedAppSettingsRoute
  '/_authenticated/business/new': typeof AuthenticatedBusinessNewRoute
  '/_authenticated/business/select': typeof AuthenticatedBusinessSelectRoute
  '/api/public/ai-jobs-worker': typeof ApiPublicAiJobsWorkerRoute
  '/_authenticated/app/': typeof AuthenticatedAppIndexRoute
  '/_authenticated/app/metrics/$metricId': typeof AuthenticatedAppMetricsMetricIdRoute
  '/_authenticated/app/operations/$processId': typeof AuthenticatedAppOperationsProcessIdRoute
  '/_authenticated/app/metrics/': typeof AuthenticatedAppMetricsIndexRoute
  '/_authenticated/app/operations/': typeof AuthenticatedAppOperationsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/reset-password'
    | '/app'
    | '/app/action-plan'
    | '/app/ai-usage'
    | '/app/blueprint'
    | '/app/brain'
    | '/app/customers'
    | '/app/dashboard'
    | '/app/diagnosis'
    | '/app/experiments'
    | '/app/help'
    | '/app/interview'
    | '/app/leads'
    | '/app/metrics'
    | '/app/notifications'
    | '/app/offers'
    | '/app/seo'
    | '/app/services'
    | '/app/settings'
    | '/business/new'
    | '/business/select'
    | '/api/public/ai-jobs-worker'
    | '/app/'
    | '/app/metrics/$metricId'
    | '/app/operations/$processId'
    | '/app/metrics/'
    | '/app/operations/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/reset-password'
    | '/app/action-plan'
    | '/app/ai-usage'
    | '/app/blueprint'
    | '/app/brain'
    | '/app/customers'
    | '/app/dashboard'
    | '/app/diagnosis'
    | '/app/experiments'
    | '/app/help'
    | '/app/interview'
    | '/app/leads'
    | '/app/notifications'
    | '/app/offers'
    | '/app/seo'
    | '/app/services'
    | '/app/settings'
    | '/business/new'
    | '/business/select'
    | '/api/public/ai-jobs-worker'
    | '/app'
    | '/app/metrics/$metricId'
    | '/app/operations/$processId'
    | '/app/metrics'
    | '/app/operations'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/reset-password'
    | '/_authenticated/app'
    | '/_authenticated/app/action-plan'
    | '/_authenticated/app/ai-usage'
    | '/_authenticated/app/blueprint'
    | '/_authenticated/app/brain'
    | '/_authenticated/app/customers'
    | '/_authenticated/app/dashboard'
    | '/_authenticated/app/diagnosis'
    | '/_authenticated/app/experiments'
    | '/_authenticated/app/help'
    | '/_authenticated/app/interview'
    | '/_authenticated/app/leads'
    | '/_authenticated/app/metrics'
    | '/_authenticated/app/notifications'
    | '/_authenticated/app/offers'
    | '/_authenticated/app/seo'
    | '/_authenticated/app/services'
    | '/_authenticated/app/settings'
    | '/_authenticated/business/new'
    | '/_authenticated/business/select'
    | '/api/public/ai-jobs-worker'
    | '/_authenticated/app/'
    | '/_authenticated/app/metrics/$metricId'
    | '/_authenticated/app/operations/$processId'
    | '/_authenticated/app/metrics/'
    | '/_authenticated/app/operations/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  ApiPublicAiJobsWorkerRoute: typeof ApiPublicAiJobsWorkerRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/app': {
      id: '/_authenticated/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AuthenticatedAppRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/app/': {
      id: '/_authenticated/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AuthenticatedAppIndexRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/action-plan': {
      id: '/_authenticated/app/action-plan'
      path: '/action-plan'
      fullPath: '/app/action-plan'
      preLoaderRoute: typeof AuthenticatedAppActionPlanRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/ai-usage': {
      id: '/_authenticated/app/ai-usage'
      path: '/ai-usage'
      fullPath: '/app/ai-usage'
      preLoaderRoute: typeof AuthenticatedAppAiUsageRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/blueprint': {
      id: '/_authenticated/app/blueprint'
      path: '/blueprint'
      fullPath: '/app/blueprint'
      preLoaderRoute: typeof AuthenticatedAppBlueprintRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/brain': {
      id: '/_authenticated/app/brain'
      path: '/brain'
      fullPath: '/app/brain'
      preLoaderRoute: typeof AuthenticatedAppBrainRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/customers': {
      id: '/_authenticated/app/customers'
      path: '/customers'
      fullPath: '/app/customers'
      preLoaderRoute: typeof AuthenticatedAppCustomersRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/dashboard': {
      id: '/_authenticated/app/dashboard'
      path: '/dashboard'
      fullPath: '/app/dashboard'
      preLoaderRoute: typeof AuthenticatedAppDashboardRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/diagnosis': {
      id: '/_authenticated/app/diagnosis'
      path: '/diagnosis'
      fullPath: '/app/diagnosis'
      preLoaderRoute: typeof AuthenticatedAppDiagnosisRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/experiments': {
      id: '/_authenticated/app/experiments'
      path: '/experiments'
      fullPath: '/app/experiments'
      preLoaderRoute: typeof AuthenticatedAppExperimentsRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/help': {
      id: '/_authenticated/app/help'
      path: '/help'
      fullPath: '/app/help'
      preLoaderRoute: typeof AuthenticatedAppHelpRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/interview': {
      id: '/_authenticated/app/interview'
      path: '/interview'
      fullPath: '/app/interview'
      preLoaderRoute: typeof AuthenticatedAppInterviewRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/leads': {
      id: '/_authenticated/app/leads'
      path: '/leads'
      fullPath: '/app/leads'
      preLoaderRoute: typeof AuthenticatedAppLeadsRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/metrics': {
      id: '/_authenticated/app/metrics'
      path: '/metrics'
      fullPath: '/app/metrics'
      preLoaderRoute: typeof AuthenticatedAppMetricsRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/notifications': {
      id: '/_authenticated/app/notifications'
      path: '/notifications'
      fullPath: '/app/notifications'
      preLoaderRoute: typeof AuthenticatedAppNotificationsRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/offers': {
      id: '/_authenticated/app/offers'
      path: '/offers'
      fullPath: '/app/offers'
      preLoaderRoute: typeof AuthenticatedAppOffersRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/seo': {
      id: '/_authenticated/app/seo'
      path: '/seo'
      fullPath: '/app/seo'
      preLoaderRoute: typeof AuthenticatedAppSeoRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/services': {
      id: '/_authenticated/app/services'
      path: '/services'
      fullPath: '/app/services'
      preLoaderRoute: typeof AuthenticatedAppServicesRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/settings': {
      id: '/_authenticated/app/settings'
      path: '/settings'
      fullPath: '/app/settings'
      preLoaderRoute: typeof AuthenticatedAppSettingsRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/business/new': {
      id: '/_authenticated/business/new'
      path: '/business/new'
      fullPath: '/business/new'
      preLoaderRoute: typeof AuthenticatedBusinessNewRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/business/select': {
      id: '/_authenticated/business/select'
      path: '/business/select'
      fullPath: '/business/select'
      preLoaderRoute: typeof AuthenticatedBusinessSelectRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/public/ai-jobs-worker': {
      id: '/api/public/ai-jobs-worker'
      path: '/api/public/ai-jobs-worker'
      fullPath: '/api/public/ai-jobs-worker'
      preLoaderRoute: typeof ApiPublicAiJobsWorkerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/app/metrics/': {
      id: '/_authenticated/app/metrics/'
      path: '/'
      fullPath: '/app/metrics/'
      preLoaderRoute: typeof AuthenticatedAppMetricsIndexRouteImport
      parentRoute: typeof AuthenticatedAppMetricsRoute
    }
    '/_authenticated/app/metrics/$metricId': {
      id: '/_authenticated/app/metrics/$metricId'
      path: '/$metricId'
      fullPath: '/app/metrics/$metricId'
      preLoaderRoute: typeof AuthenticatedAppMetricsMetricIdRouteImport
      parentRoute: typeof AuthenticatedAppMetricsRoute
    }
    '/_authenticated/app/operations/': {
      id: '/_authenticated/app/operations/'
      path: '/operations'
      fullPath: '/app/operations/'
      preLoaderRoute: typeof AuthenticatedAppOperationsIndexRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/operations/$processId': {
      id: '/_authenticated/app/operations/$processId'
      path: '/operations/$processId'
      fullPath: '/app/operations/$processId'
      preLoaderRoute: typeof AuthenticatedAppOperationsProcessIdRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
  }
}

interface AuthenticatedAppMetricsRouteChildren {
  AuthenticatedAppMetricsMetricIdRoute: typeof AuthenticatedAppMetricsMetricIdRoute
  AuthenticatedAppMetricsIndexRoute: typeof AuthenticatedAppMetricsIndexRoute
}

const AuthenticatedAppMetricsRouteChildren: AuthenticatedAppMetricsRouteChildren =
  {
    AuthenticatedAppMetricsMetricIdRoute: AuthenticatedAppMetricsMetricIdRoute,
    AuthenticatedAppMetricsIndexRoute: AuthenticatedAppMetricsIndexRoute,
  }

const AuthenticatedAppMetricsRouteWithChildren =
  AuthenticatedAppMetricsRoute._addFileChildren(
    AuthenticatedAppMetricsRouteChildren,
  )

interface AuthenticatedAppRouteChildren {
  AuthenticatedAppActionPlanRoute: typeof AuthenticatedAppActionPlanRoute
  AuthenticatedAppAiUsageRoute: typeof AuthenticatedAppAiUsageRoute
  AuthenticatedAppBlueprintRoute: typeof AuthenticatedAppBlueprintRoute
  AuthenticatedAppBrainRoute: typeof AuthenticatedAppBrainRoute
  AuthenticatedAppCustomersRoute: typeof AuthenticatedAppCustomersRoute
  AuthenticatedAppDashboardRoute: typeof AuthenticatedAppDashboardRoute
  AuthenticatedAppDiagnosisRoute: typeof AuthenticatedAppDiagnosisRoute
  AuthenticatedAppExperimentsRoute: typeof AuthenticatedAppExperimentsRoute
  AuthenticatedAppHelpRoute: typeof AuthenticatedAppHelpRoute
  AuthenticatedAppInterviewRoute: typeof AuthenticatedAppInterviewRoute
  AuthenticatedAppLeadsRoute: typeof AuthenticatedAppLeadsRoute
  AuthenticatedAppMetricsRoute: typeof AuthenticatedAppMetricsRouteWithChildren
  AuthenticatedAppNotificationsRoute: typeof AuthenticatedAppNotificationsRoute
  AuthenticatedAppOffersRoute: typeof AuthenticatedAppOffersRoute
  AuthenticatedAppSeoRoute: typeof AuthenticatedAppSeoRoute
  AuthenticatedAppServicesRoute: typeof AuthenticatedAppServicesRoute
  AuthenticatedAppSettingsRoute: typeof AuthenticatedAppSettingsRoute
  AuthenticatedAppIndexRoute: typeof AuthenticatedAppIndexRoute
  AuthenticatedAppOperationsProcessIdRoute: typeof AuthenticatedAppOperationsProcessIdRoute
  AuthenticatedAppOperationsIndexRoute: typeof AuthenticatedAppOperationsIndexRoute
}

const AuthenticatedAppRouteChildren: AuthenticatedAppRouteChildren = {
  AuthenticatedAppActionPlanRoute: AuthenticatedAppActionPlanRoute,
  AuthenticatedAppAiUsageRoute: AuthenticatedAppAiUsageRoute,
  AuthenticatedAppBlueprintRoute: AuthenticatedAppBlueprintRoute,
  AuthenticatedAppBrainRoute: AuthenticatedAppBrainRoute,
  AuthenticatedAppCustomersRoute: AuthenticatedAppCustomersRoute,
  AuthenticatedAppDashboardRoute: AuthenticatedAppDashboardRoute,
  AuthenticatedAppDiagnosisRoute: AuthenticatedAppDiagnosisRoute,
  AuthenticatedAppExperimentsRoute: AuthenticatedAppExperimentsRoute,
  AuthenticatedAppHelpRoute: AuthenticatedAppHelpRoute,
  AuthenticatedAppInterviewRoute: AuthenticatedAppInterviewRoute,
  AuthenticatedAppLeadsRoute: AuthenticatedAppLeadsRoute,
  AuthenticatedAppMetricsRoute: AuthenticatedAppMetricsRouteWithChildren,
  AuthenticatedAppNotificationsRoute: AuthenticatedAppNotificationsRoute,
  AuthenticatedAppOffersRoute: AuthenticatedAppOffersRoute,
  AuthenticatedAppSeoRoute: AuthenticatedAppSeoRoute,
  AuthenticatedAppServicesRoute: AuthenticatedAppServicesRoute,
  AuthenticatedAppSettingsRoute: AuthenticatedAppSettingsRoute,
  AuthenticatedAppIndexRoute: AuthenticatedAppIndexRoute,
  AuthenticatedAppOperationsProcessIdRoute:
    AuthenticatedAppOperationsProcessIdRoute,
  AuthenticatedAppOperationsIndexRoute: AuthenticatedAppOperationsIndexRoute,
}

const AuthenticatedAppRouteWithChildren =
  AuthenticatedAppRoute._addFileChildren(AuthenticatedAppRouteChildren)

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAppRoute: typeof AuthenticatedAppRouteWithChildren
  AuthenticatedBusinessNewRoute: typeof AuthenticatedBusinessNewRoute
  AuthenticatedBusinessSelectRoute: typeof AuthenticatedBusinessSelectRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAppRoute: AuthenticatedAppRouteWithChildren,
  AuthenticatedBusinessNewRoute: AuthenticatedBusinessNewRoute,
  AuthenticatedBusinessSelectRoute: AuthenticatedBusinessSelectRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  ApiPublicAiJobsWorkerRoute: ApiPublicAiJobsWorkerRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
